#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl12, ballHigh,       sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           feeder,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LUflywheel,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LDflywheel,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LBMdrive,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           LFdrive,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RBMdrive,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           RFdrive,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RDflywheel,    tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           RUflywheel,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          intake1,       tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
int motorSpeed = 0;
//float velocity;
int waitTime = 600;

void flywheelSpeed (int speed) {
	while(speed != motorSpeed) {
		if (speed > 127)
			speed = 127;
		else if (speed < 0)
			speed = 0;
		else if (speed + 1 == motorSpeed)
			motorSpeed -= 1;
		else if (speed < motorSpeed)
			motorSpeed -= 2;
		else if (speed - 1 == motorSpeed)
			motorSpeed += 1;
		else if (speed > motorSpeed)
			motorSpeed += 2;
		else
			motorSpeed = speed;

		motor[LUflywheel] = motorSpeed;
		motor[LDflywheel] = motorSpeed;
		motor[RUflywheel] = motorSpeed;
		motor[RUflywheel] = motorSpeed;
	}
}

task shooter(){
	while(true){
		flywheelSpeed(50);
		if (vexRT(Btn7L))
			flywheelSpeed(0);
		else if(vexRT(Btn6U) )
			flywheelSpeed(90);
		else if (vexRT(Btn6D)
		 	flywheelSpeed(127);
		wait1Msec(25);
	}
}



task drive(){
	while(true){
		motor[LFdrive] 	= vexRT(Ch2);
		motor[LBMdrive]	= vexRT(Ch2);
		motor[RFdrive] 	= vexRT(Ch3);
		motor[RBMdrive]	= vexRT(Ch3);
		wait1Msec(25);
	}
}

task loadFire(){

	while(true){
		clearTimer(T1);
		while(!SensorValue(ballHigh))
			motor[feeder] = 127;
		while(SensorValue(ballHigh)){
			if(time1(T1) < waitTime )
				motor[feeder] = 0;
			else
				motor[feeder] = 127;
		wait1Msec(200);
		}
	}
}


task intake(){ //make this shit simpler
	int swap = 0;
	while(true){
		if(vexRT(Btn8D)){
			startTask(loadFire);
			swap = 1;
		}

		if(vexRT(Btn8U)){
			stopTask(loadFire);
			motor[feeder] = 0;
			swap = 0;
		}

		if(vexRT(Btn5U)){
			motor[intake1] = 127;

		}
		if(vexRT(Btn5D)){
			motor[feeder] = 127;
		}
		if(swap == 0){
			motor[intake1] = 0;
			motor[feeder] = 0;
		}
		wait1Msec(25);
	}
}

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

bool isOkayToShoot = true;
task shootTimer() {
	isOkayToShoot = false;
	wait1Msec(waitTime);
	isOkayToShoot = true;
	endTask(autonTimer);
}

task autonomous()
{
  ClearTimer(T2);
	while(motorSpeed<90)
		flywheelSpeed(90); 		//gets it to 90 before we start loadFire
	startTask(loadFire);
	while(time1(T2)<10000)
		flywheelSpeed(90); 		//maintains 90
  while(time1(T2)>10000) 	//when there is 5 seconds left
    flywheelSpeed(0);			//begin to slow down
}

task usercontrol()
{
	startTask(shooter);
	startTask(drive);
	startTask(intake);
}
